# flake.module.nix — project-specific flake-parts customizations.
#
# seihou does NOT manage this file: it is never regenerated or overwritten by
# `seihou run` or module migrations, so it is the conflict-free home for every
# customization that must survive nix-haskell-flake template upgrades. See
# flake.module.nix.example (generated by the module) for the full option list.
#
# ┌──────────────────────────────────────────────────────────────────────────┐
# │ REQUIRED: this file MUST be git-tracked (`git add flake.module.nix`).      │
# │ Nix flakes evaluate only files tracked by git, so flake.nix's              │
# │ `builtins.pathExists ./flake.module.nix` import guard sees an untracked    │
# │ file as ABSENT and silently ignores everything below — no error, the       │
# │ customization just vanishes.                                               │
# └──────────────────────────────────────────────────────────────────────────┘
#
# This project builds a multi-package workspace with two pinned Hackage sources
# (optparse-applicative 0.19, kdl-hs 1.1.1, declared as inputs in flake.nix) and
# dhall/dhall-json rebuilt against the pinned optparse-applicative. Because it
# defines its own `packages.default` (and the sibling package outputs), the
# module is run with `nix.builtin-package = false` so the managed nix/haskell.nix
# does NOT also emit a `packages.default` (two definitions collide → flake-parts
# eval error). The dev shell, treefmt, and pre-commit wiring stay in the managed
# nix/*.nix files.
{ inputs, ... }:
{
  perSystem = { pkgs, ... }:
    let
      haskellPackages = pkgs.haskell.packages."ghc9124";

      optparseApplicativePackage =
        haskellPackages.callCabal2nix "optparse-applicative" inputs.optparse-applicative { };
      dhallPackage = haskellPackages.dhall.override {
        optparse-applicative = optparseApplicativePackage;
      };
      dhallJsonPackage = pkgs.haskell.lib.dontCheck (
        haskellPackages.dhall-json.override {
          dhall = dhallPackage;
          optparse-applicative = optparseApplicativePackage;
        }
      );
      kdlHsPackage = haskellPackages.callCabal2nix "kdl-hs" inputs.kdl-hs { };
      setteiPackage = haskellPackages.callCabal2nix "settei" ./settei { };
      setteiEnvPackage =
        haskellPackages.callCabal2nix "settei-env" ./settei-env {
          settei = setteiPackage;
        };
      setteiYamlPackage =
        haskellPackages.callCabal2nix "settei-yaml" ./settei-yaml {
          settei = setteiPackage;
        };
      setteiKdlPackage =
        haskellPackages.callCabal2nix "settei-kdl" ./settei-kdl {
          kdl-hs = kdlHsPackage;
          settei = setteiPackage;
        };
      setteiKubernetesPackage =
        haskellPackages.callCabal2nix "settei-kubernetes" ./settei-kubernetes {
          settei = setteiPackage;
          settei-env = setteiEnvPackage;
        };
      setteiDhallPackage =
        pkgs.haskell.lib.dontCheck (
          haskellPackages.callCabal2nix "settei-dhall" ./settei-dhall {
            dhall = dhallPackage;
            dhall-json = dhallJsonPackage;
            settei = setteiPackage;
          }
        );
      setteiOptparseApplicativePackage =
        # Cabal runs this package's tests with one coherent solver plan. The nixpkgs
        # tasty derivation still embeds optparse-applicative 0.18, so enabling the same
        # tests here would mix two optparse ABIs in one component graph.
        pkgs.haskell.lib.dontCheck (
          haskellPackages.callCabal2nix
            "settei-optparse-applicative"
            ./settei-optparse-applicative
            {
              optparse-applicative = optparseApplicativePackage;
              settei = setteiPackage;
              settei-env = setteiEnvPackage;
            }
        );
      setteiFormatsPackage =
        pkgs.haskell.lib.dontCheck (
          haskellPackages.callCabal2nix "settei-formats" ./settei-formats {
            optparse-applicative = optparseApplicativePackage;
            settei = setteiPackage;
            settei-dhall = setteiDhallPackage;
            settei-kdl = setteiKdlPackage;
            settei-optparse-applicative = setteiOptparseApplicativePackage;
            settei-yaml = setteiYamlPackage;
          }
        );
      setteiExampleCliPackage =
        pkgs.haskell.lib.dontCheck (
          haskellPackages.callCabal2nix "settei-example-cli" ./examples/settei-cli {
            optparse-applicative = optparseApplicativePackage;
            settei = setteiPackage;
            settei-env = setteiEnvPackage;
            settei-formats = setteiFormatsPackage;
            settei-optparse-applicative = setteiOptparseApplicativePackage;
          }
        );
      setteiExampleServicePackage =
        pkgs.haskell.lib.dontCheck (
          haskellPackages.callCabal2nix "settei-example-service" ./examples/settei-service {
            optparse-applicative = optparseApplicativePackage;
            settei = setteiPackage;
            settei-env = setteiEnvPackage;
            settei-formats = setteiFormatsPackage;
            settei-kubernetes = setteiKubernetesPackage;
            settei-optparse-applicative = setteiOptparseApplicativePackage;
            settei-yaml = setteiYamlPackage;
          }
        );
      setteiExampleConformancePackage =
        # Cabal is the test authority for these examples. nixpkgs' tasty closure still
        # carries optparse-applicative 0.18, while the examples deliberately test the
        # workspace's pinned 0.19 API, so Nix builds their test-free package artifacts.
        pkgs.haskell.lib.dontCheck (
          haskellPackages.callCabal2nix
            "settei-example-conformance"
            ./examples/settei-conformance
            {
              optparse-applicative = optparseApplicativePackage;
              settei = setteiPackage;
              settei-dhall = setteiDhallPackage;
              settei-env = setteiEnvPackage;
              settei-example-cli = setteiExampleCliPackage;
              settei-example-service = setteiExampleServicePackage;
              settei-kdl = setteiKdlPackage;
              settei-kubernetes = setteiKubernetesPackage;
              settei-optparse-applicative = setteiOptparseApplicativePackage;
              settei-yaml = setteiYamlPackage;
            }
        );
    in
    {
      packages.default = setteiPackage;
      packages.settei-example-cli = setteiExampleCliPackage;
      packages.settei-example-conformance = setteiExampleConformancePackage;
      packages.settei-example-service = setteiExampleServicePackage;
      packages.settei-dhall = setteiDhallPackage;
      packages.settei-env = setteiEnvPackage;
      packages.settei-formats = setteiFormatsPackage;
      packages.settei-kdl = setteiKdlPackage;
      packages.settei-kubernetes = setteiKubernetesPackage;
      packages.settei-optparse-applicative = setteiOptparseApplicativePackage;
      packages.settei-yaml = setteiYamlPackage;

      # Keep both profile-governed documentation bundles strictly validated and
      # verify that their Markdown link graphs remain readable. `okf` is not in
      # nixpkgs, so this system hook uses the copy already available on PATH.
      pre-commit.settings.hooks.okf-documentation-check = {
        enable = true;
        name = "okf-documentation-check";
        description = "Validate and graph the repository's profiled OKF documentation.";
        entry = "${pkgs.writeShellScript "okf-documentation-check" ''
          set -eu
          okf validate docs/adr --strict --profile docs/adr/profile.dhall --profile-enforce --log-enforce
          okf graph docs/adr --json >/dev/null
          okf validate docs/guides --strict --profile mori/user-documentation-profile.dhall --profile-enforce --log-enforce
          okf graph docs/guides --json >/dev/null
        ''}";
        language = "system";
        pass_filenames = false;
        files = "^(docs/(adr|guides)/|mori/user-documentation-profile\\.dhall$|mori\\.dhall$)";
      };
    };
}
