apiVersion: v1
kind: ConfigMap
metadata:
  name: settei-example-service
data:
  HASKELL_ENV: production
  application.yaml: |
    http:
      host: 0.0.0.0
    database:
      host: postgres.production.internal
      port: 5432
