apiVersion: apps/v1
kind: Deployment
metadata:
  name: settei-example-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: settei-example-service
  template:
    metadata:
      labels:
        app: settei-example-service
    spec:
      containers:
        - name: service
          image: example.invalid/settei-example-service:replace-me
          args:
            - --config
            - yaml:/etc/settei/application.yaml
            - --explain-config
          env:
            - name: HASKELL_ENV
              value: production
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: settei-example-service-database
                  key: password
          volumeMounts:
            - name: configuration
              mountPath: /etc/settei
              readOnly: true
      volumes:
        - name: configuration
          configMap:
            name: settei-example-service
